### PR TITLE
Load v_repLib runtime library and add initial scaffolding

### LINKED ISSUE #1: vrep plugin skeleton implementation
The initial implementation that just sets up all the scaffolding necessary for existing as a vrep plugin.

### PR DESCRIPTION
**Pull request by kgreenek**
Closes #1

### CODE REVIEW

**Review by imcnanie — APPROVED** [review]
Great, thanks! Now I can get to work on my stuff! I like that the V-REP license says we're free to use their code for any purpose, that's whats up. Looks super clean.

**Comment by kgreenek** [comment]
Schweet!Oh, where did you find their license? I could find it. Link?

**Comment by imcnanie** [comment]
https://github.com/kgreenek/vrep_px4/blob/scaffolding/vendor/vrep/include/vrep/v_repTypes.h

**Comment by kgreenek** [comment]
That comment says it's GPL3 (or commercial if you contact them and work out an arrangement).
No worries. Guess our license is GPL3

**Pull request merged**
